import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import { Toaster } from "@/components/ui/sonner";

import './globals.css'
import Header from "@/components/Header";

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${nunito.className} bg-background text-gray-900 antialiased`}>
      <Header />

        <main className="isolate flex flex-col gap-40">
          {children}
        </main>
        {/* {children} */}
        <Toaster richColors />

      </body>
    </html>
  )
}
